branches:
  only:
    - master

language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4

env:
  - REQUIREMENTS=1.4.X
  - REQUIREMENTS=1.5.X
  - REQUIREMENTS=1.6.X
  - REQUIREMENTS=1.7.X
  - REQUIREMENTS=master

matrix:
  exclude:
    - python: 2.6
      env: REQUIREMENTS=1.7.X
    - python: 2.6
      env: REQUIREMENTS=master
    - python: 3.2
      env: REQUIREMENTS=1.4.X
    - python: 3.2
      env: REQUIREMENTS=master
    - python: 3.3
      env: REQUIREMENTS=1.4.X
    - python: 3.3
      env: REQUIREMENTS=master
    - python: 3.4
      env: REQUIREMENTS=1.4.X
    - python: 3.4
      env: REQUIREMENTS=1.5.X
    - python: 3.4
      env: REQUIREMENTS=1.6.X
  allow_failures:
    - env: REQUIREMENTS=1.7.X
    - env: REQUIREMENTS=master

install:
  - pip install -r requirements/$REQUIREMENTS.txt -q --use-mirrors
  - pip install -e . --use-mirrors
  - pip install coveralls

script: coverage run runtests.py --omit="*/site-packages/*"

after_success:
  - coverage report -m --omit="*/site-packages/*"
  - coveralls
